export enum RemoteTypeChoices {
  FULL_REMOTE_WORK = "FULL_REMOTE_WORK",
  PARTIAL_REMOTE_WORK = "PARTIAL_REMOTE_WORK",
  NO_REMOTE_WORK = "NO_REMOTE_WORK",
}
export enum CategoryChoices {
  MOBILEDEVELOPER = "MOBILEDEVELOPER",
  FRONTEND = "FRONTEND",
  OTHER = "OTHER",
  DEVOPS = "DEVOPS",
  FULLSTACK = "FULLSTACK",
  BACKEND = "BACKEND",
  TEAM_LEADER = "TEAM_LEADER",
  DATABASEDEVELOPER = "DATABASEDEVELOPER",
  TESTER = "TESTER",
  SUPPORT = "SUPPORT",
  BUSINESSANALYST = "BUSINESSANALYST",
  ADMINISTRATOR = "ADMINISTRATOR",
  PROJECTMANAGER = "PROJECTMANAGER",
  SECURITY = "SECURITY",
  EMBEDDEDSYSTEMSDEVELOPER = "EMBEDDEDSYSTEMSDEVELOPER",
  ARCHITECT = "ARCHITECT",
  AI_MACHINELEARNING = "AI_MACHINELEARNING",
  GAMEDEV = "GAMEDEV",
  UXUIDESIGNER = "UXUIDESIGNER",
  TRAINER = "TRAINER",
}
export enum B2bFrequencyChoices {
  HOUR = "HOUR",
  MONTH = "MONTH",
}
export enum EmploymentFrequencyChoices {
  MONTH = "MONTH",
  HOUR = "HOUR",
  YEAR = "YEAR",
}
