name: Main

on: [push, pull_request]


jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'npm install eslint'
      - run: 'node ./node_modules/eslint/bin/eslint.js .'
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://node:14
      - run: "npm install"
      - run: "npm install gulp"
      - run: "gulp build"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - run: 'npm install jest'
      - run: 'node ./node_modules/jest/bin/jest.js'
