name: Main

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://node:14
      - run: "pwd"
      - run: "npm install"
      - run: "npm install gulp"
      - run: "gulp build"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: "npm install jest"
      - run: "jest"
