name: Main

on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: "Prepare Node"
        uses: docker://node:14
      - name: "Checkout data"
        uses: actions/checkout@v2
      - name: "Install dependencies"
        run: "npm install"
      - name: "Linter"
        run: "node ./node_modules/eslint/bin/eslint.js ."
      - name: "Build"
        run: "gulp build"
      - name: "Test"
        run: "node ./node_modules/jest/bin/jest.js"
